import type { Port } from "./types";

export const ZED_SCHEMA_URL = "https://zed.dev/schema/themes/v0.2.0.json";

export const zed: Port = {
  id: "zed",
  file: "ports/zed/arkham.json",
  render(p) {
    const { ui, syntax, ansi } = p;
    const style = {
      "background": ui.background,
      "background.appearance": "opaque",
      "surface.background": ui.sidebar,
      "elevated_surface.background": ui.input,
      "border": ui.sidebarHeaderBorder,
      "border.variant": ui.sidebarBorder,
      "border.focused": ui.selection,
      "border.selected": ui.accent,
      "border.transparent": "#00000000",
      "border.disabled": ui.sidebarBorder,
      "text": ui.foreground,
      "text.muted": ui.lineNumber,
      "text.placeholder": ui.ignored,
      "text.disabled": ui.ignored,
      "text.accent": ui.accent,
      "icon": ui.activityForeground,
      "icon.muted": ui.lineNumber,
      "icon.disabled": ui.ignored,
      "icon.placeholder": ui.lineNumber,
      "icon.accent": ui.accent,
      "status_bar.background": ui.statusBar,
      "title_bar.background": ui.background,
      "title_bar.inactive_background": ui.background,
      "toolbar.background": ui.background,
      "tab_bar.background": ui.background,
      "tab.active_background": ui.background,
      "tab.inactive_background": ui.tabInactive,
      "panel.background": ui.sidebar,
      "panel.focused_border": ui.accent,
      "pane.focused_border": ui.accent,
      "pane_group.border": ui.sidebarBorder,
      "element.background": ui.input,
      "element.hover": ui.listHover,
      "element.active": ui.listInactiveSelection,
      "element.selected": ui.listInactiveSelection,
      "element.disabled": ui.tabInactive,
      "ghost_element.background": "#00000000",
      "ghost_element.hover": ui.listHover,
      "ghost_element.active": ui.listInactiveSelection,
      "ghost_element.selected": ui.listInactiveSelection,
      "ghost_element.disabled": ui.tabInactive,
      "drop_target.background": ui.selectionHighlight,
      "scrollbar.thumb.background": ui.selection,
      "scrollbar.thumb.hover_background": ui.lineNumber,
      "scrollbar.thumb.border": ui.selection,
      "scrollbar.track.background": ui.background,
      "scrollbar.track.border": ui.sidebarBorder,
      "search.match_background": ui.findMatch,
      "editor.background": ui.background,
      "editor.foreground": ui.foreground,
      "editor.gutter.background": ui.background,
      "editor.subheader.background": ui.sidebar,
      "editor.active_line.background": ui.tabHover,
      "editor.highlighted_line.background": ui.tabHover,
      "editor.line_number": ui.lineNumber,
      "editor.active_line_number": ui.foreground,
      "editor.invisible": ui.ignored,
      "editor.wrap_guide": ui.sidebarHeaderBorder,
      "editor.active_wrap_guide": ui.selection,
      "editor.indent_guide": ui.sidebarHeaderBorder,
      "editor.indent_guide_active": ui.selection,
      "editor.document_highlight.read_background": ui.wordHighlight,
      "editor.document_highlight.write_background": ui.findMatch,
      "editor.document_highlight.bracket_background": ui.wordHighlight,
      "terminal.background": ui.background,
      "terminal.foreground": ui.foreground,
      "terminal.bright_foreground": ansi.brightWhite,
      "terminal.dim_foreground": ui.lineNumber,
      "terminal.ansi.background": ui.background,
      "terminal.ansi.black": ansi.black,
      "terminal.ansi.red": ansi.red,
      "terminal.ansi.green": ansi.green,
      "terminal.ansi.yellow": ansi.yellow,
      "terminal.ansi.blue": ansi.blue,
      "terminal.ansi.magenta": ansi.magenta,
      "terminal.ansi.cyan": ansi.cyan,
      "terminal.ansi.white": ansi.white,
      "terminal.ansi.bright_black": ansi.brightBlack,
      "terminal.ansi.bright_red": ansi.brightRed,
      "terminal.ansi.bright_green": ansi.brightGreen,
      "terminal.ansi.bright_yellow": ansi.brightYellow,
      "terminal.ansi.bright_blue": ansi.brightBlue,
      "terminal.ansi.bright_magenta": ansi.brightMagenta,
      "terminal.ansi.bright_cyan": ansi.brightCyan,
      "terminal.ansi.bright_white": ansi.brightWhite,
      "link_text.hover": syntax.method,
      "error": syntax.invalid,
      "error.background": ui.background,
      "error.border": syntax.invalid,
      "warning": syntax.class,
      "warning.background": ui.background,
      "warning.border": syntax.class,
      "success": syntax.function,
      "success.background": ui.background,
      "success.border": syntax.function,
      "info": syntax.method,
      "info.background": ui.background,
      "info.border": syntax.method,
      "hint": ui.lineNumber,
      "hint.background": ui.background,
      "hint.border": ui.lineNumber,
      "predictive": ui.ignored,
      "created": syntax.inserted,
      "modified": syntax.changed,
      "deleted": syntax.invalid,
      "conflict": syntax.tag,
      "renamed": syntax.method,
      "ignored": ui.ignored,
      "hidden": ui.ignored,
      "unreachable": ui.lineNumber,
      "players": [
        { cursor: ui.accent, selection: ui.selection, background: ui.accent },
        { cursor: syntax.function, selection: ui.selectionHighlight, background: syntax.function },
        { cursor: syntax.method, selection: ui.selectionHighlight, background: syntax.method },
        { cursor: syntax.class, selection: ui.selectionHighlight, background: syntax.class },
      ],
      "syntax": {
        "attribute": { color: syntax.attribute, font_style: "italic" },
        "boolean": { color: syntax.constant },
        "comment": { color: syntax.comment, font_style: "italic" },
        "comment.doc": { color: syntax.comment, font_style: "italic" },
        "constant": { color: syntax.constant },
        "constructor": { color: syntax.class },
        "embedded": { color: syntax.variable },
        "emphasis": { font_style: "italic" },
        "emphasis.strong": { font_weight: 700 },
        "enum": { color: syntax.constant },
        "function": { color: syntax.function },
        "hint": { color: ui.lineNumber },
        "keyword": { color: syntax.keyword },
        "label": { color: syntax.constant },
        "link_text": { color: syntax.method },
        "link_uri": { color: syntax.method },
        "number": { color: syntax.constant },
        "operator": { color: syntax.keyword },
        "predictive": { color: ui.ignored },
        "preproc": { color: syntax.keyword },
        "primary": { color: syntax.variable },
        "property": { color: syntax.variable },
        "punctuation": { color: syntax.keyword },
        "punctuation.bracket": { color: syntax.keyword },
        "punctuation.delimiter": { color: syntax.variable },
        "punctuation.list_marker": { color: syntax.keyword },
        "punctuation.special": { color: syntax.keyword },
        "string": { color: syntax.string },
        "string.escape": { color: syntax.regexp },
        "string.regex": { color: syntax.regexp },
        "string.special": { color: syntax.string },
        "string.special.symbol": { color: syntax.string },
        "tag": { color: syntax.tag },
        "text.literal": { color: syntax.changed },
        "title": { color: syntax.inserted },
        "type": { color: syntax.class },
        "variable": { color: syntax.variable },
        "variable.special": { color: syntax.invalid, font_style: "italic" },
      },
    };
    const theme = {
      $schema: ZED_SCHEMA_URL,
      name: p.name,
      author: p.author,
      themes: [{ name: p.name, appearance: "dark", style }],
    };
    return JSON.stringify(theme, null, 2) + "\n";
  },
};
