# Arkham
color0 #23263c
color1 #ff5370
color2 #2de4a1
color3 #ffdf89
color4 #82aaff
color5 #ff67b1
color6 #89ddff
color7 #dad6da
color8 #8988a0
color9 #ff8a9e
color10 #7cf0c4
color11 #ffeab5
color12 #a9c6ff
color13 #b289f1
color14 #b3ebff
color15 #f6f3fc
background #161526
foreground #dad6da
cursor #ff70b1
cursor_text_color #161526
selection_background #6a6793
selection_foreground #f6f3fc
